"""Constantes y estados controlados del módulo interno Bot WhatsApp."""

CONVERSATION_STATUS_OPEN = "open"
CONVERSATION_STATUS_PENDING_HUMAN = "pending_human"
CONVERSATION_STATUS_BOT_PAUSED = "bot_paused"
CONVERSATION_STATUS_RESOLVED = "resolved"
CONVERSATION_STATUS_ARCHIVED = "archived"
CONVERSATION_STATUSES = {
    CONVERSATION_STATUS_OPEN,
    CONVERSATION_STATUS_PENDING_HUMAN,
    CONVERSATION_STATUS_BOT_PAUSED,
    CONVERSATION_STATUS_RESOLVED,
    CONVERSATION_STATUS_ARCHIVED,
}

MESSAGE_DIRECTION_INBOUND = "inbound"
MESSAGE_DIRECTION_OUTBOUND = "outbound"
MESSAGE_DIRECTIONS = {MESSAGE_DIRECTION_INBOUND, MESSAGE_DIRECTION_OUTBOUND}

MESSAGE_STATUS_INBOUND_RECEIVED = "received"
MESSAGE_STATUS_INBOUND_PARSED = "parsed"
MESSAGE_STATUS_INBOUND_STORED = "stored"
MESSAGE_STATUS_INBOUND_INVALID = "invalid"
MESSAGE_STATUS_OUTBOUND_QUEUED = "queued"
MESSAGE_STATUS_OUTBOUND_SENT = "sent"
MESSAGE_STATUS_OUTBOUND_DELIVERED = "delivered"
MESSAGE_STATUS_OUTBOUND_READ = "read"
MESSAGE_STATUS_OUTBOUND_FAILED = "failed"
MESSAGE_STATUS_OUTBOUND_CANCELED = "canceled"
MESSAGE_STATUSES = {
    MESSAGE_STATUS_INBOUND_RECEIVED,
    MESSAGE_STATUS_INBOUND_PARSED,
    MESSAGE_STATUS_INBOUND_STORED,
    MESSAGE_STATUS_INBOUND_INVALID,
    MESSAGE_STATUS_OUTBOUND_QUEUED,
    MESSAGE_STATUS_OUTBOUND_SENT,
    MESSAGE_STATUS_OUTBOUND_DELIVERED,
    MESSAGE_STATUS_OUTBOUND_READ,
    MESSAGE_STATUS_OUTBOUND_FAILED,
    MESSAGE_STATUS_OUTBOUND_CANCELED,
}

IDENTITY_STATUS_UNKNOWN = "unknown"
IDENTITY_STATUS_NEW_CONTACT = "new_contact"
IDENTITY_STATUS_CLIENT_IDENTIFIED = "client_identified"
IDENTITY_STATUS_CANDIDATE_IDENTIFIED = "candidate_identified"
IDENTITY_STATUS_CLIENT_AND_CANDIDATE = "client_and_candidate"
IDENTITY_STATUS_AMBIGUOUS = "ambiguous"
IDENTITY_STATUS_BLOCKED = "blocked"
IDENTITY_STATUSES = {
    IDENTITY_STATUS_UNKNOWN,
    IDENTITY_STATUS_NEW_CONTACT,
    IDENTITY_STATUS_CLIENT_IDENTIFIED,
    IDENTITY_STATUS_CANDIDATE_IDENTIFIED,
    IDENTITY_STATUS_CLIENT_AND_CANDIDATE,
    IDENTITY_STATUS_AMBIGUOUS,
    IDENTITY_STATUS_BLOCKED,
}

DECISION_TYPE_IDENTIFY_CONTACT = "identify_contact"
DECISION_TYPE_AUTO_REPLY = "auto_reply"
DECISION_TYPE_AI_CLASSIFICATION = "ai_classification"
DECISION_TYPE_JOB_SEND_ELIGIBILITY = "job_send_eligibility"
DECISION_TYPE_ESCALATION = "escalation"
DECISION_TYPE_SAFETY_BLOCK = "safety_block"
DECISION_TYPE_PROTOCOL_STEP_CHANGE = "protocol_step_change"
DECISION_TYPE_PROTOCOL_AUTO_ADVANCE = "protocol_auto_advance"
DECISION_TYPE_PROTOCOL_PENDING_CORRECTION = "protocol_pending_correction"
DECISION_TYPE_PROTOCOL_CORRECTION_APPROVED = "protocol_correction_approved"
DECISION_TYPE_PROTOCOL_CORRECTION_REJECTED = "protocol_correction_rejected"
DECISION_TYPES = {
    DECISION_TYPE_IDENTIFY_CONTACT,
    DECISION_TYPE_AUTO_REPLY,
    DECISION_TYPE_AI_CLASSIFICATION,
    DECISION_TYPE_JOB_SEND_ELIGIBILITY,
    DECISION_TYPE_ESCALATION,
    DECISION_TYPE_SAFETY_BLOCK,
    DECISION_TYPE_PROTOCOL_STEP_CHANGE,
    DECISION_TYPE_PROTOCOL_AUTO_ADVANCE,
    DECISION_TYPE_PROTOCOL_PENDING_CORRECTION,
    DECISION_TYPE_PROTOCOL_CORRECTION_APPROVED,
    DECISION_TYPE_PROTOCOL_CORRECTION_REJECTED,
}

DECISION_RESULT_ALLOW = "allow"
DECISION_RESULT_DENY = "deny"
DECISION_RESULT_ESCALATE = "escalate"
DECISION_RESULT_MANUAL_ONLY = "manual_only"
DECISION_RESULT_DEFER = "defer"
DECISION_RESULTS = {
    DECISION_RESULT_ALLOW,
    DECISION_RESULT_DENY,
    DECISION_RESULT_ESCALATE,
    DECISION_RESULT_MANUAL_ONLY,
    DECISION_RESULT_DEFER,
}

ESCALATION_STATUS_OPEN = "open"
ESCALATION_STATUS_ACKNOWLEDGED = "acknowledged"
ESCALATION_STATUS_RESOLVED = "resolved"
ESCALATION_STATUS_CANCELED = "canceled"
ESCALATION_STATUSES = {
    ESCALATION_STATUS_OPEN,
    ESCALATION_STATUS_ACKNOWLEDGED,
    ESCALATION_STATUS_RESOLVED,
    ESCALATION_STATUS_CANCELED,
}

MESSAGE_SOURCE_WHATSAPP_USER = "whatsapp_user"
MESSAGE_SOURCE_ADMIN_MANUAL = "admin_manual"
MESSAGE_SOURCE_BOT_AUTO = "bot_auto"
MESSAGE_SOURCE_SYSTEM = "system"
MESSAGE_SOURCES = {
    MESSAGE_SOURCE_WHATSAPP_USER,
    MESSAGE_SOURCE_ADMIN_MANUAL,
    MESSAGE_SOURCE_BOT_AUTO,
    MESSAGE_SOURCE_SYSTEM,
}

# Intents seguros cerrados para Fase 4
INTENT_FAQ_HORARIOS = "FAQ_HORARIOS"
INTENT_FAQ_REQUISITOS = "FAQ_REQUISITOS"
INTENT_FAQ_UBICACION = "FAQ_UBICACION"
INTENT_FAQ_CONTACTO = "FAQ_CONTACTO"
INTENT_FAQ_ESTADO_GENERAL = "FAQ_ESTADO_GENERAL"
INTENT_HUMAN_REQUEST = "HUMAN_REQUEST"
INTENT_UNKNOWN = "UNKNOWN"

SAFE_INTENTS = {
    INTENT_FAQ_HORARIOS,
    INTENT_FAQ_REQUISITOS,
    INTENT_FAQ_UBICACION,
    INTENT_FAQ_CONTACTO,
    INTENT_FAQ_ESTADO_GENERAL,
    INTENT_HUMAN_REQUEST,
    INTENT_UNKNOWN,
}
