"""Refactor Cliente: quitar auth y location, agregar sector

Revision ID: 00802568522a
Revises: 2b78df2752aa
Create Date: 2025-07-10 22:10:55.830053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00802568522a'
down_revision = '2b78df2752aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', sa.String(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_clientes_username'), type_='unique')
        batch_op.drop_column('provincia')
        batch_op.drop_column('direccion')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('direccion', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('provincia', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_clientes_username'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('sector')

    # ### end Alembic commands ###
