"""crear tabla candidatas_web

Revision ID: 016660676fb3
Revises: 57d526d014c1
Create Date: 2025-11-27 19:55:48.806012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016660676fb3'
down_revision = '57d526d014c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
