"""add referencias laborales y familiares a reclutas

Revision ID: 18d97f857f25
Revises: 7d517d214e46
Create Date: 2026-01-05 13:09:37.034930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d97f857f25'
down_revision = '7d517d214e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reclutas_perfiles', sa.Column('referencias_laborales', sa.Text(), nullable=True, comment='Referencias laborales: nombres, teléfonos y relación.'))
    op.add_column('reclutas_perfiles', sa.Column('referencias_familiares', sa.Text(), nullable=True, comment='Referencias familiares: nombres, teléfonos y relación.'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reclutas_perfiles', 'referencias_familiares')
    op.drop_column('reclutas_perfiles', 'referencias_laborales')
    # ### end Alembic commands ###
