"""Make ninos nullable

Revision ID: 1d4dee73c43b
Revises: 4abd10665b17
Create Date: 2025-06-29 10:31:58.746569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4dee73c43b'
down_revision = '4abd10665b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.alter_column('ninos',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.alter_column('ninos',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
