"""reconcile prod drift core objects and indexes (idempotent, non-destructive)

Revision ID: 20260329_1100
Revises: 20260328_1830
Create Date: 2026-03-29 11:00:00
"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "20260329_1100"
down_revision = "20260328_1830"
branch_labels = None
depends_on = None


def _ensure_postgres() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        raise RuntimeError("Reconciliacion preparada para PostgreSQL.")


def upgrade():
    _ensure_postgres()

    # Ajustes defensivos para evitar esperas largas de lock en prod.
    op.execute("SET lock_timeout = '5s'")
    op.execute("SET statement_timeout = '60s'")

    # 1) solicitud: columna faltante (nullable)
    op.execute(
        """
        ALTER TABLE public.solicitudes
        ADD COLUMN IF NOT EXISTS fecha_seguimiento_manual date
        """
    )

    # 2) request_idempotency_keys
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS public.request_idempotency_keys (
            id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            scope varchar(80) NOT NULL,
            idempotency_key varchar(128) NOT NULL,
            actor_id varchar(64),
            entity_type varchar(50),
            entity_id varchar(64),
            request_hash varchar(64) NOT NULL,
            response_status integer,
            response_code varchar(80),
            created_at timestamp without time zone NOT NULL,
            last_seen_at timestamp without time zone NOT NULL
        )
        """
    )

    # 3) domain_outbox base + columnas posteriores
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS public.domain_outbox (
            id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            event_id varchar(64) NOT NULL,
            event_type varchar(80) NOT NULL,
            aggregate_type varchar(80) NOT NULL,
            aggregate_id varchar(64) NOT NULL,
            aggregate_version integer,
            occurred_at timestamp without time zone NOT NULL,
            actor_id varchar(64),
            region varchar(40),
            payload jsonb NOT NULL DEFAULT '{}'::jsonb,
            published_at timestamp without time zone,
            created_at timestamp without time zone NOT NULL
        )
        """
    )

    op.execute(
        """
        ALTER TABLE public.domain_outbox
        ADD COLUMN IF NOT EXISTS schema_version integer NOT NULL DEFAULT 1
        """
    )
    op.execute(
        """
        ALTER TABLE public.domain_outbox
        ADD COLUMN IF NOT EXISTS correlation_id varchar(64)
        """
    )
    op.execute(
        """
        ALTER TABLE public.domain_outbox
        ADD COLUMN IF NOT EXISTS idempotency_key varchar(128)
        """
    )
    op.execute(
        """
        ALTER TABLE public.domain_outbox
        ADD COLUMN IF NOT EXISTS published_attempts integer NOT NULL DEFAULT 0
        """
    )
    op.execute(
        """
        ALTER TABLE public.domain_outbox
        ADD COLUMN IF NOT EXISTS last_error varchar(500)
        """
    )
    op.execute(
        """
        ALTER TABLE public.domain_outbox
        ADD COLUMN IF NOT EXISTS last_attempt_at timestamp without time zone
        """
    )
    op.execute(
        """
        ALTER TABLE public.domain_outbox
        ADD COLUMN IF NOT EXISTS next_retry_at timestamp without time zone
        """
    )
    op.execute(
        """
        ALTER TABLE public.domain_outbox
        ADD COLUMN IF NOT EXISTS relay_status varchar(20) DEFAULT 'pending'
        """
    )
    op.execute(
        """
        ALTER TABLE public.domain_outbox
        ADD COLUMN IF NOT EXISTS first_failed_at timestamp without time zone
        """
    )
    op.execute(
        """
        ALTER TABLE public.domain_outbox
        ADD COLUMN IF NOT EXISTS quarantined_at timestamp without time zone
        """
    )
    op.execute(
        """
        ALTER TABLE public.domain_outbox
        ADD COLUMN IF NOT EXISTS quarantine_reason varchar(80)
        """
    )

    # 4) outbox_consumer_receipts
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS public.outbox_consumer_receipts (
            id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            consumer_name varchar(80) NOT NULL,
            event_id varchar(64) NOT NULL,
            processed_at timestamp without time zone NOT NULL
        )
        """
    )

    # 5) operational_metric_snapshots
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS public.operational_metric_snapshots (
            id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            captured_at timestamp without time zone NOT NULL,
            window_minutes integer NOT NULL DEFAULT 15,
            metrics jsonb NOT NULL DEFAULT '{}'::jsonb
        )
        """
    )

    # 6) Índices concurrentes (separados en bloque autocommit)
    ctx = op.get_context()
    with ctx.autocommit_block():
        # solicitudes
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_solicitudes_fecha_seguimiento_manual "
            "ON public.solicitudes (fecha_seguimiento_manual)"
        )

        # request_idempotency_keys
        op.execute(
            "CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS "
            "uq_request_idempotency_scope_key "
            "ON public.request_idempotency_keys (scope, idempotency_key)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_request_idempotency_scope "
            "ON public.request_idempotency_keys (scope)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_request_idempotency_scope_actor "
            "ON public.request_idempotency_keys (scope, actor_id)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_request_idempotency_actor "
            "ON public.request_idempotency_keys (actor_id)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_request_idempotency_entity_type "
            "ON public.request_idempotency_keys (entity_type)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_request_idempotency_entity_id "
            "ON public.request_idempotency_keys (entity_id)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_request_idempotency_created_at "
            "ON public.request_idempotency_keys (created_at)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_request_idempotency_last_seen_at "
            "ON public.request_idempotency_keys (last_seen_at)"
        )

        # domain_outbox
        op.execute(
            "CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS "
            "uq_domain_outbox_event_id "
            "ON public.domain_outbox (event_id)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_domain_outbox_event_type "
            "ON public.domain_outbox (event_type)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_domain_outbox_aggregate_type "
            "ON public.domain_outbox (aggregate_type)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_domain_outbox_aggregate_id "
            "ON public.domain_outbox (aggregate_id)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_domain_outbox_aggregate_version "
            "ON public.domain_outbox (aggregate_version)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_domain_outbox_occurred_at "
            "ON public.domain_outbox (occurred_at)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_domain_outbox_actor_id "
            "ON public.domain_outbox (actor_id)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_domain_outbox_published_at "
            "ON public.domain_outbox (published_at)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_domain_outbox_created_at "
            "ON public.domain_outbox (created_at)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_domain_outbox_aggregate "
            "ON public.domain_outbox (aggregate_type, aggregate_id)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_domain_outbox_published_created "
            "ON public.domain_outbox (published_at, created_at)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_domain_outbox_correlation_id "
            "ON public.domain_outbox (correlation_id)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_domain_outbox_idempotency_key "
            "ON public.domain_outbox (idempotency_key)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_domain_outbox_next_retry_at "
            "ON public.domain_outbox (next_retry_at)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_domain_outbox_relay_status "
            "ON public.domain_outbox (relay_status)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_domain_outbox_quarantined_at "
            "ON public.domain_outbox (quarantined_at)"
        )

        # outbox_consumer_receipts
        op.execute(
            "CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS "
            "uq_outbox_consumer_event "
            "ON public.outbox_consumer_receipts (consumer_name, event_id)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_outbox_consumer_receipts_consumer_name "
            "ON public.outbox_consumer_receipts (consumer_name)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_outbox_consumer_receipts_event_id "
            "ON public.outbox_consumer_receipts (event_id)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_outbox_consumer_receipts_processed_at "
            "ON public.outbox_consumer_receipts (processed_at)"
        )

        # operational_metric_snapshots
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
            "ix_operational_metric_snapshots_captured_at "
            "ON public.operational_metric_snapshots (captured_at)"
        )


def downgrade():
    # Reconciliacion no destructiva: downgrade intencionalmente vacio.
    pass
