"""Add foto_perfil to candidatas

Revision ID: 206235f23660
Revises: 5256130bc22c
Create Date: 2025-07-12 23:28:05.153435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206235f23660'
down_revision = '5256130bc22c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidatas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil', sa.LargeBinary(), nullable=True, comment='Foto de la candidata para su perfil'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidatas', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil')

    # ### end Alembic commands ###
