"""Add fecha_ultima_modificacion to Solicitud

Revision ID: 2b78df2752aa
Revises: 08049de0496d
Create Date: 2025-07-09 23:06:59.745991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b78df2752aa'
down_revision = '08049de0496d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_ultima_modificacion', sa.DateTime(), nullable=True))
        batch_op.alter_column('edad_requerida',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               type_=sa.String(length=200),
               nullable=True,
               existing_server_default=sa.text('ARRAY[]::character varying[]'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.alter_column('edad_requerida',
               existing_type=sa.String(length=200),
               type_=postgresql.ARRAY(sa.VARCHAR(length=50)),
               nullable=False,
               existing_server_default=sa.text('ARRAY[]::character varying[]'))
        batch_op.drop_column('fecha_ultima_modificacion')

    # ### end Alembic commands ###
