"""expandir_precision_numeric

Revision ID: 3eab79c80270
Revises: 89e54a150506
Create Date: 2025-06-14 12:57:36.429216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eab79c80270'
down_revision = '89e54a150506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
