"""remove codigo and inscripcion from reclutas

Revision ID: 413cbc98a27d
Revises: 18d97f857f25
Create Date: 2026-01-06 14:37:02.481026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '413cbc98a27d'
down_revision = '18d97f857f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reclutas_perfiles_codigo'), table_name='reclutas_perfiles')
    op.drop_index(op.f('ix_reclutas_perfiles_inscrito'), table_name='reclutas_perfiles')
    op.drop_column('reclutas_perfiles', 'inscripcion_fecha')
    op.drop_column('reclutas_perfiles', 'inscripcion_via')
    op.drop_column('reclutas_perfiles', 'inscripcion_monto')
    op.drop_column('reclutas_perfiles', 'codigo')
    op.drop_column('reclutas_perfiles', 'inscrito')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reclutas_perfiles', sa.Column('inscrito', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='True si ya fue inscrito (pagó inscripción y se le asignó código).'))
    op.add_column('reclutas_perfiles', sa.Column('codigo', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('reclutas_perfiles', sa.Column('inscripcion_monto', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True, comment='Monto pagado por inscripción (ej: 500.00).'))
    op.add_column('reclutas_perfiles', sa.Column('inscripcion_via', postgresql.ENUM('oficina', 'transferencia', name='recluta_inscripcion_via_enum'), autoincrement=False, nullable=True, comment='Vía de inscripción: oficina o transferencia.'))
    op.add_column('reclutas_perfiles', sa.Column('inscripcion_fecha', sa.DATE(), autoincrement=False, nullable=True, comment='Fecha en que se realizó la inscripción.'))
    op.create_index(op.f('ix_reclutas_perfiles_inscrito'), 'reclutas_perfiles', ['inscrito'], unique=False)
    op.create_index(op.f('ix_reclutas_perfiles_codigo'), 'reclutas_perfiles', ['codigo'], unique=True)
    # ### end Alembic commands ###
