"""inscripcion reclutas: codigo nullable + campos pago/fecha/via

Revision ID: 460a658df914
Revises: bcdc516585ba
Create Date: 2026-01-05 11:18:28.640593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460a658df914'
down_revision = 'bcdc516585ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Crear el ENUM en PostgreSQL antes de usarlo en ALTER TABLE
    recluta_inscripcion_via_enum = sa.Enum('oficina', 'transferencia', name='recluta_inscripcion_via_enum')
    recluta_inscripcion_via_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('reclutas_perfiles', sa.Column('inscrito', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='True si ya fue inscrito (pagó inscripción y se le asignó código).'))
    op.add_column('reclutas_perfiles', sa.Column('inscripcion_monto', sa.Numeric(precision=12, scale=2), nullable=True, comment='Monto pagado por inscripción (ej: 500.00).'))
    op.add_column('reclutas_perfiles', sa.Column('inscripcion_fecha', sa.Date(), nullable=True, comment='Fecha en que se realizó la inscripción.'))
    op.add_column('reclutas_perfiles', sa.Column('inscripcion_via', sa.Enum('oficina', 'transferencia', name='recluta_inscripcion_via_enum'), nullable=True, comment='Vía de inscripción: oficina o transferencia.'))
    op.alter_column('reclutas_perfiles', 'codigo',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.create_index(op.f('ix_reclutas_perfiles_inscrito'), 'reclutas_perfiles', ['inscrito'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reclutas_perfiles_inscrito'), table_name='reclutas_perfiles')
    op.alter_column('reclutas_perfiles', 'codigo',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('reclutas_perfiles', 'inscripcion_via')
    op.drop_column('reclutas_perfiles', 'inscripcion_fecha')
    op.drop_column('reclutas_perfiles', 'inscripcion_monto')
    op.drop_column('reclutas_perfiles', 'inscrito')
    # Eliminar el ENUM si ya no se usa
    recluta_inscripcion_via_enum = sa.Enum('oficina', 'transferencia', name='recluta_inscripcion_via_enum')
    recluta_inscripcion_via_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
