"""Add fecha_finalizacion_proceso and grupos_empleo to candidatas

Revision ID: 5256130bc22c
Revises: 1d39e2382335
Create Date: 2025-07-12 23:18:19.269882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5256130bc22c'
down_revision = '1d39e2382335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidatas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_finalizacion_proceso', sa.DateTime(), nullable=True, comment='Fecha en que la candidata completa el cuestionario de finalización de proceso'))
        batch_op.add_column(sa.Column('grupos_empleo', postgresql.ARRAY(sa.String(length=100)), server_default=sa.text('ARRAY[]::VARCHAR[]'), nullable=True, comment='Lista de grupos de empleo asignados a la candidata'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidatas', schema=None) as batch_op:
        batch_op.drop_column('grupos_empleo')
        batch_op.drop_column('fecha_finalizacion_proceso')

    # ### end Alembic commands ###
