"""Agregar tipo_servicio y detalles_servicio

Revision ID: 57d526d014c1
Revises: 7286c98ef4e0
Create Date: 2025-11-22 22:10:25.764265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d526d014c1'
down_revision = '7286c98ef4e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
