"""add tipo y opciones to entrevista_preguntas

Revision ID: 61e4ce9b0a08
Revises: dd28287460ec
Create Date: 2026-01-03 12:53:43.207234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61e4ce9b0a08'
down_revision = 'dd28287460ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrevista_preguntas', sa.Column('tipo', sa.String(length=30), server_default=sa.text("'texto'"), nullable=False, comment='Tipo de campo: texto, texto_largo, radio, etc.'))
    op.add_column('entrevista_preguntas', sa.Column('opciones', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Opciones para tipo=radio (lista). Ej: ['Sí','No']"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entrevista_preguntas', 'opciones')
    op.drop_column('entrevista_preguntas', 'tipo')
    # ### end Alembic commands ###
