"""Crear tabla candidatas

Revision ID: 69abe8ab1d37
Revises: ade340025a54
Create Date: 2025-06-18 11:56:10.385865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69abe8ab1d37'
down_revision = 'ade340025a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidatas', 'edad',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('candidatas', 'anos_experiencia',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidatas', 'anos_experiencia',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('candidatas', 'edad',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
