"""Agregar tipo_servicio y detalles_servicio a Solicitud

Revision ID: 7286c98ef4e0
Revises: 016f584231cb
Create Date: 2025-11-21 22:10:10.737897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7286c98ef4e0'
down_revision = '016f584231cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitudes', sa.Column('tipo_servicio', sa.String(length=50), nullable=True, comment='Tipo de servicio solicitado: DOMESTICA_LIMPIEZA, NINERA, ENFERMERA, CHOFER, etc.'))
    op.add_column('solicitudes', sa.Column('detalles_servicio', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Bloque de respuestas específicas según el tipo de servicio (niñera, chofer, etc.).'))
    op.create_index(op.f('ix_solicitudes_tipo_servicio'), 'solicitudes', ['tipo_servicio'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitudes_tipo_servicio'), table_name='solicitudes')
    op.drop_column('solicitudes', 'detalles_servicio')
    op.drop_column('solicitudes', 'tipo_servicio')
    # ### end Alembic commands ###
