"""fix duplicated models

Revision ID: 7321c841875f
Revises: a214d9bb230b
Create Date: 2026-01-03 12:34:21.226693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7321c841875f'
down_revision = 'a214d9bb230b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrevista_preguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False, comment='Clave interna: ej. tiene_hijos, sabe_cocinar'),
    sa.Column('texto', sa.String(length=255), nullable=False, comment='Texto visible de la pregunta'),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrevista_preguntas_clave'), 'entrevista_preguntas', ['clave'], unique=True)
    op.create_table('entrevistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidata_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False, comment='Estado de la entrevista: completa / borrador'),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.Column('actualizada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidata_id'], ['candidatas.fila'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrevistas_candidata_id'), 'entrevistas', ['candidata_id'], unique=False)
    op.create_table('entrevista_respuestas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrevista_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=True),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.Column('actualizada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entrevista_id'], ['entrevistas.id'], ),
    sa.ForeignKeyConstraint(['pregunta_id'], ['entrevista_preguntas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrevista_respuestas_entrevista_id'), 'entrevista_respuestas', ['entrevista_id'], unique=False)
    op.create_index(op.f('ix_entrevista_respuestas_pregunta_id'), 'entrevista_respuestas', ['pregunta_id'], unique=False)
    op.alter_column('candidatas', 'compat_estilo_trabajo',
               existing_type=postgresql.ENUM('necesita_instrucciones', 'toma_iniciativa', name='compat_estilo_enum'),
               type_=sa.Enum('necesita_instrucciones', 'toma_iniciativa', name='compat_estilo_enum'),
               existing_comment='Prefiere instrucciones o tomar iniciativa.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidatas', 'compat_estilo_trabajo',
               existing_type=sa.Enum('necesita_instrucciones', 'toma_iniciativa', name='compat_estilo_enum'),
               type_=postgresql.ENUM('necesita_instrucciones', 'toma_iniciativa', name='compat_estilo_enum'),
               existing_comment='Prefiere instrucciones o tomar iniciativa.',
               existing_nullable=True)
    op.drop_index(op.f('ix_entrevista_respuestas_pregunta_id'), table_name='entrevista_respuestas')
    op.drop_index(op.f('ix_entrevista_respuestas_entrevista_id'), table_name='entrevista_respuestas')
    op.drop_table('entrevista_respuestas')
    op.drop_index(op.f('ix_entrevistas_candidata_id'), table_name='entrevistas')
    op.drop_table('entrevistas')
    op.drop_index(op.f('ix_entrevista_preguntas_clave'), table_name='entrevista_preguntas')
    op.drop_table('entrevista_preguntas')
    # ### end Alembic commands ###
