"""Crear tabla llamadas_candidatas

Revision ID: 77b4a92b1690
Revises: 206235f23660
Create Date: 2025-07-17 23:50:01.195402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b4a92b1690'
down_revision = '206235f23660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llamadas_candidatas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidata_id', sa.Integer(), nullable=False),
    sa.Column('fecha_llamada', sa.DateTime(), nullable=False),
    sa.Column('resultado', sa.String(length=100), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidata_id'], ['candidatas.fila'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llamadas_candidatas')
    # ### end Alembic commands ###
