"""Initial schema from models

Revision ID: 7d3bf97cec7a
Revises: 
Create Date: 2025-05-26 16:35:10.394027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d3bf97cec7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # op.drop_table('candidata')  # comentada porque la tabla no existe en una DB nueva

    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidata',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('marca_temporal', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('nombre_completo', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('edad', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('numero_telefono', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('direccion_completa', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('modalidad_trabajo', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('rutas_cercanas', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('empleo_anterior', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('anos_experiencia', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('areas_experiencia', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('monto_inscripcion', sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column('fecha_inscripcion', sa.DATE(), autoincrement=False, nullable=True),
        sa.Column('fecha_pago', sa.DATE(), autoincrement=False, nullable=True),
        sa.Column('inicio', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('monto_total', sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column('porcentaje', sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column('calificacion', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('entrevista', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('depuracion', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('perfil', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('cedula1', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('cedula2', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('referencias_laborales', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('referencias_familiares', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('acepta_porcentaje', sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column('cedula', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('codigo', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('medio_inscripcion', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('inscripcion', sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('candidata_pkey'))
    )
    # ### end Alembic commands ###
