"""add referencias laborales y familiares a reclutas

Revision ID: 7d517d214e46
Revises: 460a658df914
Create Date: 2026-01-05 13:05:18.818376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d517d214e46'
down_revision = '460a658df914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
