"""Create all tables from models

Revision ID: 810ba48aeab1
Revises: 7d3bf97cec7a
Create Date: 2025-06-08 12:24:12.119293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810ba48aeab1'
down_revision = '7d3bf97cec7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidatas',
    sa.Column('fila', sa.Integer(), nullable=False),
    sa.Column('marca_temporal', sa.DateTime(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('numero_telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion_completa', sa.String(length=300), nullable=True),
    sa.Column('modalidad_trabajo_preferida', sa.String(length=100), nullable=True),
    sa.Column('rutas_cercanas', sa.String(length=200), nullable=True),
    sa.Column('empleo_anterior', sa.Text(), nullable=True),
    sa.Column('anos_experiencia', sa.Integer(), nullable=True),
    sa.Column('areas_experiencia', sa.Text(), nullable=True),
    sa.Column('sabe_planchar', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('contactos_referencias_laborales', sa.Text(), nullable=True),
    sa.Column('referencias_familiares_detalle', sa.Text(), nullable=True),
    sa.Column('acepta_porcentaje_sueldo', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cedula', sa.String(length=50), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('medio_inscripcion', sa.String(length=100), nullable=True),
    sa.Column('inscripcion', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('fecha_de_pago', sa.Date(), nullable=True),
    sa.Column('inicio', sa.Date(), nullable=True),
    sa.Column('monto_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('porciento', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('calificacion', sa.String(length=100), nullable=True),
    sa.Column('entrevista', sa.Text(), nullable=True),
    sa.Column('depuracion', sa.String(length=300), nullable=True),
    sa.Column('perfil', sa.String(length=300), nullable=True),
    sa.Column('cedula1', sa.String(length=300), nullable=True),
    sa.Column('cedula2', sa.String(length=300), nullable=True),
    sa.Column('referencias_laboral', sa.Text(), nullable=True),
    sa.Column('referencias_familiares', sa.Text(), nullable=True),
    sa.CheckConstraint('acepta_porcentaje_sueldo BETWEEN -999.99 AND 999.99', name='chk_acepta_porcentaje'),
    sa.CheckConstraint('porciento BETWEEN -999.99 AND 999.99', name='chk_porciento'),
    sa.PrimaryKeyConstraint('fila')
    )
    op.create_index(op.f('ix_candidatas_cedula'), 'candidatas', ['cedula'], unique=True)
    op.create_index(op.f('ix_candidatas_codigo'), 'candidatas', ['codigo'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidatas_codigo'), table_name='candidatas')
    op.drop_index(op.f('ix_candidatas_cedula'), table_name='candidatas')
    op.drop_table('candidatas')
    # ### end Alembic commands ###
