"""Add cancel fields to Solicitud

Revision ID: 86884a7b8012
Revises: c84be1d1f02e
Create Date: 2025-06-29 09:57:38.211842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86884a7b8012'
down_revision = 'c84be1d1f02e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_cancelacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('motivo_cancelacion', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_column('motivo_cancelacion')
        batch_op.drop_column('fecha_cancelacion')

    # ### end Alembic commands ###
