"""Añadir candidata_id y monto_pagado a solicitudes

Revision ID: 8b7cf2048363
Revises: 656b3174ee61
Create Date: 2025-06-25 17:32:26.275554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7cf2048363'
down_revision = '656b3174ee61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidata_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monto_pagado', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'candidatas', ['candidata_id'], ['fila'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('monto_pagado')
        batch_op.drop_column('candidata_id')

    # ### end Alembic commands ###
