"""actualizacion CandidataWeb

Revision ID: a214d9bb230b
Revises: f33360c7437a
Create Date: 2025-11-27 20:44:20.344719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a214d9bb230b'
down_revision = 'f33360c7437a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
