"""add username and password_hash to clientes

Revision ID: af1696bceec6
Revises: defa0a881018
Create Date: 2026-02-12 11:31:55.779876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af1696bceec6'
down_revision = 'defa0a881018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1) Add username (nullable) + unique index
    op.add_column('clientes', sa.Column('username', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_clientes_username'), 'clientes', ['username'], unique=True)

    # 2) Add password_hash safely for existing rows
    #    - server_default ensures the ADD COLUMN works even if the table already has rows.
    op.add_column(
        'clientes',
        sa.Column(
            'password_hash',
            sa.String(length=255),
            nullable=False,
            server_default=sa.text("'DISABLED_RESET_REQUIRED'")
        )
    )

    # 3) IMPORTANT: Do NOT drop any existing columns here.
    #    Alembic sometimes thinks columns were removed if there are synonyms/renames.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_clientes_username'), table_name='clientes')
    op.drop_column('clientes', 'password_hash')
    op.drop_column('clientes', 'username')

    # ### end Alembic commands ###
