"""create reclutas_perfiles

Revision ID: bcdc516585ba
Revises: d9c47ede821b
Create Date: 2026-01-05 10:40:56.558391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcdc516585ba'
down_revision = 'd9c47ede821b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reclutas_perfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.Enum('nuevo', 'aprobado', 'rechazado', name='estado_recluta_enum'), server_default=sa.text("'nuevo'"), nullable=False, comment='Estado interno del perfil reclutado'),
    sa.Column('creado_por', sa.String(length=100), nullable=True, comment='Usuario/Nombre (admin o secretaria) que creó el perfil'),
    sa.Column('actualizado_por', sa.String(length=100), nullable=True, comment='Usuario/Nombre (admin o secretaria) que actualizó por última vez'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('cedula', sa.String(length=50), nullable=False),
    sa.Column('edad', sa.String(length=20), nullable=True, comment="Edad en texto: '25', '30-35', etc"),
    sa.Column('sexo', sa.Enum('masculino', 'femenino', 'otro', name='sexo_recluta_enum'), nullable=True),
    sa.Column('nacionalidad', sa.String(length=80), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('direccion_completa', sa.String(length=300), nullable=True, comment='Dirección completa (incluye ciudad/sector si aplica)'),
    sa.Column('ciudad', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('tipos_empleo_busca', postgresql.ARRAY(sa.String(length=50)), server_default=sa.text('ARRAY[]::VARCHAR[]'), nullable=True, comment='Lista de tipos de empleo que busca (NO doméstica)'),
    sa.Column('empleo_principal', sa.String(length=50), nullable=True, comment='Tipo de empleo principal preferido (NO doméstica)'),
    sa.Column('modalidad', sa.Enum('tiempo_completo', 'medio_tiempo', 'por_dias', 'por_horas', name='modalidad_recluta_enum'), nullable=True),
    sa.Column('horario_disponible', sa.String(length=120), nullable=True),
    sa.Column('sueldo_esperado', sa.String(length=80), nullable=True, comment="Texto libre: 'RD$25,000', 'a discutir', 'por día', etc"),
    sa.Column('tiene_experiencia', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('anos_experiencia', sa.String(length=20), nullable=True),
    sa.Column('experiencia_resumen', sa.String(length=300), nullable=True, comment='Resumen corto (1-2 líneas)'),
    sa.Column('nivel_educativo', sa.String(length=80), nullable=True, comment='Ej: primaria, secundaria, técnico, universitario'),
    sa.Column('habilidades', sa.String(length=300), nullable=True, comment='Ej: computadora, caja, servicio al cliente, Excel, etc'),
    sa.Column('documentos_al_dia', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Si tiene documentos al día (según verificación rápida)'),
    sa.Column('disponible_fines_o_noches', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Si puede fines de semana o noches'),
    sa.Column('observaciones_internas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reclutas_perfiles_cedula'), 'reclutas_perfiles', ['cedula'], unique=False)
    op.create_index(op.f('ix_reclutas_perfiles_ciudad'), 'reclutas_perfiles', ['ciudad'], unique=False)
    op.create_index(op.f('ix_reclutas_perfiles_codigo'), 'reclutas_perfiles', ['codigo'], unique=True)
    op.create_index(op.f('ix_reclutas_perfiles_email'), 'reclutas_perfiles', ['email'], unique=False)
    op.create_index(op.f('ix_reclutas_perfiles_empleo_principal'), 'reclutas_perfiles', ['empleo_principal'], unique=False)
    op.create_index(op.f('ix_reclutas_perfiles_estado'), 'reclutas_perfiles', ['estado'], unique=False)
    op.create_index(op.f('ix_reclutas_perfiles_modalidad'), 'reclutas_perfiles', ['modalidad'], unique=False)
    op.create_index(op.f('ix_reclutas_perfiles_nombre_completo'), 'reclutas_perfiles', ['nombre_completo'], unique=False)
    op.create_index(op.f('ix_reclutas_perfiles_sector'), 'reclutas_perfiles', ['sector'], unique=False)
    op.create_index(op.f('ix_reclutas_perfiles_telefono'), 'reclutas_perfiles', ['telefono'], unique=False)
    op.create_index(op.f('ix_reclutas_perfiles_tiene_experiencia'), 'reclutas_perfiles', ['tiene_experiencia'], unique=False)
    op.create_table('reclutas_cambios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recluta_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False, comment='Ej: creado, editado, aprobado, rechazado'),
    sa.Column('usuario', sa.String(length=100), nullable=True, comment='Usuario/Nombre que realizó el cambio'),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recluta_id'], ['reclutas_perfiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reclutas_cambios_creado_en'), 'reclutas_cambios', ['creado_en'], unique=False)
    op.create_index(op.f('ix_reclutas_cambios_recluta_id'), 'reclutas_cambios', ['recluta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reclutas_cambios_recluta_id'), table_name='reclutas_cambios')
    op.drop_index(op.f('ix_reclutas_cambios_creado_en'), table_name='reclutas_cambios')
    op.drop_table('reclutas_cambios')
    op.drop_index(op.f('ix_reclutas_perfiles_tiene_experiencia'), table_name='reclutas_perfiles')
    op.drop_index(op.f('ix_reclutas_perfiles_telefono'), table_name='reclutas_perfiles')
    op.drop_index(op.f('ix_reclutas_perfiles_sector'), table_name='reclutas_perfiles')
    op.drop_index(op.f('ix_reclutas_perfiles_nombre_completo'), table_name='reclutas_perfiles')
    op.drop_index(op.f('ix_reclutas_perfiles_modalidad'), table_name='reclutas_perfiles')
    op.drop_index(op.f('ix_reclutas_perfiles_estado'), table_name='reclutas_perfiles')
    op.drop_index(op.f('ix_reclutas_perfiles_empleo_principal'), table_name='reclutas_perfiles')
    op.drop_index(op.f('ix_reclutas_perfiles_email'), table_name='reclutas_perfiles')
    op.drop_index(op.f('ix_reclutas_perfiles_codigo'), table_name='reclutas_perfiles')
    op.drop_index(op.f('ix_reclutas_perfiles_ciudad'), table_name='reclutas_perfiles')
    op.drop_index(op.f('ix_reclutas_perfiles_cedula'), table_name='reclutas_perfiles')
    op.drop_table('reclutas_perfiles')
    # ### end Alembic commands ###
