"""Actualizar modelos: campos nuevos en Solicitud/Cliente

Revision ID: d2766f8b4d8a
Revises: 72c072e0308d
Create Date: 2025-11-16 12:14:51.369919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2766f8b4d8a'
down_revision = '72c072e0308d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'en_progreso', 'completada', name='estado_tarea_cliente_enum'), nullable=False),
    sa.Column('prioridad', sa.Enum('baja', 'media', 'alta', name='prioridad_tarea_cliente_enum'), nullable=False),
    sa.Column('completada_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tareas_clientes_cliente_id'), 'tareas_clientes', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_tareas_clientes_fecha_vencimiento'), 'tareas_clientes', ['fecha_vencimiento'], unique=False)
    op.alter_column('candidatas', 'compat_test_candidata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Respuestas completas del test/entrevista de la candidata (estructura JSON).',
               existing_comment='Respuestas completas del test/entrevista de la candidata (JSON).',
               existing_nullable=True)
    op.alter_column('candidatas', 'compat_limites_no_negociables',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=100)),
               comment='Límites declarados (p. ej.: no mascotas, no cocinar, no dormir fuera).',
               existing_comment='Límites (p. ej.: no mascotas, no cocinar, no dormir fuera).',
               existing_nullable=True,
               existing_server_default=sa.text('ARRAY[]::character varying[]'))
    op.alter_column('clientes', 'fecha_acepto_politicas',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha y hora en que aceptó las políticas.',
               existing_comment='Fecha/hora en que aceptó por primera vez.',
               existing_nullable=True)
    op.drop_constraint(op.f('uq_clientes_codigo'), 'clientes', type_='unique')
    op.drop_index(op.f('ix_clientes_codigo'), table_name='clientes')
    op.create_index(op.f('ix_clientes_codigo'), 'clientes', ['codigo'], unique=True)
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=True)
    op.alter_column('solicitudes', 'compat_test_cliente_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Respuestas del test del CLIENTE (estructura JSON) para esta solicitud.',
               existing_comment='Respuestas del test del CLIENTE (JSON).',
               existing_nullable=True)
    op.alter_column('solicitudes', 'compat_test_cliente_version',
               existing_type=sa.VARCHAR(length=20),
               comment='Versión del cuestionario del cliente (para futuras migraciones).',
               existing_comment='Versión del cuestionario del cliente.',
               existing_nullable=True)
    op.alter_column('solicitudes', 'compat_calc_summary',
               existing_type=sa.TEXT(),
               comment='Coincidencias clave y explicación breve del resultado.',
               existing_comment='Coincidencias clave y explicación breve.',
               existing_nullable=True)
    op.alter_column('solicitudes', 'compat_calc_risks',
               existing_type=sa.TEXT(),
               comment='Riesgos/alertas detectados (no negociables, horarios, etc.).',
               existing_comment='Riesgos/alertas (no negociables, horarios, etc.).',
               existing_nullable=True)
    op.alter_column('solicitudes', 'compat_pdf_path',
               existing_type=sa.VARCHAR(length=255),
               comment='Ruta/filename del PDF generado con el informe de compatibilidad.',
               existing_comment='Ruta/filename del PDF de compatibilidad.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solicitudes', 'compat_pdf_path',
               existing_type=sa.VARCHAR(length=255),
               comment='Ruta/filename del PDF de compatibilidad.',
               existing_comment='Ruta/filename del PDF generado con el informe de compatibilidad.',
               existing_nullable=True)
    op.alter_column('solicitudes', 'compat_calc_risks',
               existing_type=sa.TEXT(),
               comment='Riesgos/alertas (no negociables, horarios, etc.).',
               existing_comment='Riesgos/alertas detectados (no negociables, horarios, etc.).',
               existing_nullable=True)
    op.alter_column('solicitudes', 'compat_calc_summary',
               existing_type=sa.TEXT(),
               comment='Coincidencias clave y explicación breve.',
               existing_comment='Coincidencias clave y explicación breve del resultado.',
               existing_nullable=True)
    op.alter_column('solicitudes', 'compat_test_cliente_version',
               existing_type=sa.VARCHAR(length=20),
               comment='Versión del cuestionario del cliente.',
               existing_comment='Versión del cuestionario del cliente (para futuras migraciones).',
               existing_nullable=True)
    op.alter_column('solicitudes', 'compat_test_cliente_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Respuestas del test del CLIENTE (JSON).',
               existing_comment='Respuestas del test del CLIENTE (estructura JSON) para esta solicitud.',
               existing_nullable=True)
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=False)
    op.drop_index(op.f('ix_clientes_codigo'), table_name='clientes')
    op.create_index(op.f('ix_clientes_codigo'), 'clientes', ['codigo'], unique=False)
    op.create_unique_constraint(op.f('uq_clientes_codigo'), 'clientes', ['codigo'], postgresql_nulls_not_distinct=False)
    op.alter_column('clientes', 'fecha_acepto_politicas',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha/hora en que aceptó por primera vez.',
               existing_comment='Fecha y hora en que aceptó las políticas.',
               existing_nullable=True)
    op.alter_column('candidatas', 'compat_limites_no_negociables',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=100)),
               comment='Límites (p. ej.: no mascotas, no cocinar, no dormir fuera).',
               existing_comment='Límites declarados (p. ej.: no mascotas, no cocinar, no dormir fuera).',
               existing_nullable=True,
               existing_server_default=sa.text('ARRAY[]::character varying[]'))
    op.alter_column('candidatas', 'compat_test_candidata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Respuestas completas del test/entrevista de la candidata (JSON).',
               existing_comment='Respuestas completas del test/entrevista de la candidata (estructura JSON).',
               existing_nullable=True)
    op.drop_index(op.f('ix_tareas_clientes_fecha_vencimiento'), table_name='tareas_clientes')
    op.drop_index(op.f('ix_tareas_clientes_cliente_id'), table_name='tareas_clientes')
    op.drop_table('tareas_clientes')
    # ### end Alembic commands ###
