"""add reclutamiento general (no domestica)

Revision ID: d9c47ede821b
Revises: 61e4ce9b0a08
Create Date: 2026-01-05 10:19:58.016722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c47ede821b'
down_revision = '61e4ce9b0a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
