"""fix compat_estilo_enum name

Revision ID: dd28287460ec
Revises: 7321c841875f
Create Date: 2026-01-03 12:45:14.267415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd28287460ec'
down_revision = '7321c841875f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
