"""add tipo to entrevistas

Revision ID: defa0a881018
Revises: c1f3c2b61aaa
Create Date: 2026-01-21 10:51:49.513713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'defa0a881018'
down_revision = 'c1f3c2b61aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entrevista_preguntas', 'clave',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=120),
               comment='Clave interna: ej. domestica.tiene_hijos, enfermera.experiencia, etc.',
               existing_comment='Clave interna: ej. tiene_hijos, sabe_cocinar',
               existing_nullable=False)
    op.add_column('entrevistas', sa.Column('tipo', sa.String(length=30), server_default=sa.text("'domestica'"), nullable=False, comment='Tipo de entrevista: domestica / enfermera / empleo_general'))
    op.create_index(op.f('ix_entrevistas_tipo'), 'entrevistas', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entrevistas_tipo'), table_name='entrevistas')
    op.drop_column('entrevistas', 'tipo')
    op.alter_column('entrevista_preguntas', 'clave',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=50),
               comment='Clave interna: ej. tiene_hijos, sabe_cocinar',
               existing_comment='Clave interna: ej. domestica.tiene_hijos, enfermera.experiencia, etc.',
               existing_nullable=False)
    # ### end Alembic commands ###
