"""crear tabla candidatas_web

Revision ID: f33360c7437a
Revises: 016660676fb3
Create Date: 2025-11-27 20:33:29.535440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33360c7437a'
down_revision = '016660676fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidatas_web',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidata_id', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Si está en True, la candidata aparece en la web pública.'),
    sa.Column('estado_publico', sa.Enum('disponible', 'reservada', 'no_disponible', name='estado_publico_candidata_enum'), server_default=sa.text("'disponible'"), nullable=False, comment='Estado visible para el cliente en la web.'),
    sa.Column('es_destacada', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Si es True, se muestra como candidata destacada.'),
    sa.Column('orden_lista', sa.Integer(), nullable=True, comment='Orden manual en la lista pública (1,2,3...).'),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=False, comment='Cuándo se publicó por primera vez en la web.'),
    sa.Column('fecha_ultima_actualizacion', sa.DateTime(), nullable=False, comment='Última vez que se actualizó esta ficha web.'),
    sa.Column('nombre_publico', sa.String(length=200), nullable=True, comment='Nombre que se muestra en la web. Si es NULL, se usa el nombre real.'),
    sa.Column('edad_publica', sa.String(length=50), nullable=True, comment="Texto libre de edad: '37 años', 'Mayor de 45 años', etc."),
    sa.Column('ciudad_publica', sa.String(length=120), nullable=True, comment='Ciudad que se muestra al cliente.'),
    sa.Column('sector_publico', sa.String(length=120), nullable=True, comment='Sector o zona de referencia para el cliente.'),
    sa.Column('modalidad_publica', sa.String(length=120), nullable=True, comment='Modalidad visible: con dormida, sin dormida, por días, etc.'),
    sa.Column('tipo_servicio_publico', sa.String(length=50), nullable=True, comment='Tipo de servicio: DOMESTICA, NINERA, ENFERMERA, etc.'),
    sa.Column('anos_experiencia_publicos', sa.String(length=50), nullable=True, comment="Texto de años de experiencia: '5 años', 'Más de 10 años', etc."),
    sa.Column('experiencia_resumen', sa.Text(), nullable=True, comment='Resumen corto que sale en la tarjeta de la lista.'),
    sa.Column('experiencia_detallada', sa.Text(), nullable=True, comment='Descripción más larga para la página de detalle.'),
    sa.Column('tags_publicos', sa.String(length=255), nullable=True, comment="Lista de tags separados por coma: 'Limpieza, Cocina básica, Niñera'."),
    sa.Column('frase_destacada', sa.String(length=200), nullable=True, comment='Frase llamativa para enganchar al cliente.'),
    sa.Column('sueldo_desde', sa.Integer(), nullable=True, comment='Rango mínimo sugerido de sueldo en RD$ (solo referencia).'),
    sa.Column('sueldo_hasta', sa.Integer(), nullable=True, comment='Rango máximo sugerido de sueldo en RD$ (solo referencia).'),
    sa.Column('sueldo_texto_publico', sa.String(length=120), nullable=True, comment="Texto que se muestra: 'RD$16,000 en adelante', 'Según horario', etc."),
    sa.Column('foto_publica_url', sa.String(length=255), nullable=True, comment='URL de la foto que se muestra en la web. Si está NULL, usas la de la BD interna.'),
    sa.Column('disponible_inmediato', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Si está disponible para iniciar de inmediato.'),
    sa.ForeignKeyConstraint(['candidata_id'], ['candidatas.fila'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidatas_web_candidata_id'), 'candidatas_web', ['candidata_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidatas_web_candidata_id'), table_name='candidatas_web')
    op.drop_table('candidatas_web')
    # ### end Alembic commands ###
