"""Convertir rutas de imagen a LargeBinary

Revision ID: f8be62737073
Revises: xxxx
Create Date: 2025-06-14 15:04:06.554509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8be62737073'
down_revision = 'xxxx'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'candidatas', 'depuracion',
        existing_type=sa.VARCHAR(length=300),
        type_=sa.LargeBinary(),
        existing_nullable=True,
        postgresql_using='depuracion::bytea'
    )
    op.alter_column(
        'candidatas', 'perfil',
        existing_type=sa.VARCHAR(length=300),
        type_=sa.LargeBinary(),
        existing_nullable=True,
        postgresql_using='perfil::bytea'
    )
    op.alter_column(
        'candidatas', 'cedula1',
        existing_type=sa.VARCHAR(length=300),
        type_=sa.LargeBinary(),
        existing_nullable=True,
        postgresql_using='cedula1::bytea'
    )
    op.alter_column(
        'candidatas', 'cedula2',
        existing_type=sa.VARCHAR(length=300),
        type_=sa.LargeBinary(),
        existing_nullable=True,
        postgresql_using='cedula2::bytea'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'candidatas', 'cedula2',
        existing_type=sa.LargeBinary(),
        type_=sa.VARCHAR(length=300),
        existing_nullable=True,
        postgresql_using='cedula2::varchar'
    )
    op.alter_column(
        'candidatas', 'cedula1',
        existing_type=sa.LargeBinary(),
        type_=sa.VARCHAR(length=300),
        existing_nullable=True,
        postgresql_using='cedula1::varchar'
    )
    op.alter_column(
        'candidatas', 'perfil',
        existing_type=sa.LargeBinary(),
        type_=sa.VARCHAR(length=300),
        existing_nullable=True,
        postgresql_using='perfil::varchar'
    )
    op.alter_column(
        'candidatas', 'depuracion',
        existing_type=sa.LargeBinary(),
        type_=sa.VARCHAR(length=300),
        existing_nullable=True,
        postgresql_using='depuracion::varchar'
    )
    # ### end Alembic commands ###
